version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=@#Hellosk5491@#
      - DB_NAME=backend_auth
      - JWT_SECRET=@#Hellosk5491@#
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: @#Hellosk5491@#
      MYSQL_DATABASE: backend_auth
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
